baseURL = "/"
languageCode = "en-us"
title = "Butler"
theme = ["docsy"]
description = "Butler adds features and services to Qlik Sense Enterprise on Windows, making it easier to develop for and operate QSEoW."
Paginate = 20

# Added to support publishing to GitHub Pages, as per https://gohugo.io/hosting-and-deployment/hosting-on-github/
publishDir = "docs"

# SEO
enableRobotsTXT = true

# Docsy: Gives values to .Lastmod etc.
enableGitInfo = true

# Docsy: Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
# Tell Hugo not to include the /en/ element in the URL path for English docs:
defaultContentLanguageInSubdir = false
# Docsy: Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Docsy: Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

 # Docsy: First one is picked as the Twitter card image if not set on page.
 #images = ["images/project-illustration.png"]

# Top-level navigation (horizontal)

[[menu.main]]
    name = "What is Butler?"
    weight = -103
    url = "/docs/about/butler/"
[[menu.main]]
    name = "Documentation"
    weight = -101
    url = "/docs/"
# [[menu.main]]
#     name = "Community"
#     weight = -100
#     url = "https://ptarmiganlabs.com"
[[menu.main]]
    name = "Blog"
    weight = -99
    url = "https://ptarmiganlabs.com"
[[menu.main]]
    name = "The Butler family"
    weight = -98
    url = "/docs/about/butler-family"
# [[menu.main]]
#     name = "GitHub"
#     weight = -97
#     url = "https://github.com/ptarmiganlabs/butler"

# Docsy: Configure the format of URLs per section.
#[permalinks]
#blog = "/:section/:year/:month/:day/:slug/"

# Docsy: Configuration for Goldmark markdown parser, which is default from 
# Hugo 0.60 onwards. https://github.com/yuin/goldmark/
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
# Allow Goldmark to render raw HTML:
      unsafe = true

# Docsy: Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
id = "UA-58487795-5"

# Docsy: Language configuration

[languages]
[languages.en]
title = "Butler"
description = "Butler adds features and services to Qlik Sense Enterprise on Windows, making it easier to develop for and operate QSEoW."
languageName ="English"
# Weight used for sorting in the language menu:
weight = 1

# Below is an example of another language (Norwegian):
#[languages.no]
#title = "Docsy"
#description = "Docsy er operativsystem for skyen"
#languageName ="Norsk"
#contentDir = "content/no"
time_format_default = "2006-01-02"
time_format_blog = "2006-01-02"

# Site params

[params]

# GitHub repository for in-page links to editing a page and opening and issues.
github_repo = "https://github.com/ptarmiganlabs/butler-docs"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/ptarmiganlabs/butler"

RSSLink = "/index.xml"
author = "Ptarmigan Labs" # add your company name
github = "ptarmiganlabs" # add your github profile name
twitter = "ptarmiganlabs" # add your twitter profile
email = "info@ptarmiganlabs.com"

copyright = "Ptarmigan Labs AB"
# privacy_policy = "https://policies.google.com/privacy"

# Docsy: Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Text label for the version menu in the top bar of the website.
version_menu = "v4.0"

# The major.minor version tag for the version of the docs represented in this
# branch of the repository. Used in the "version-banner" partial to display a
# version number for this doc set.
version = "v4.0"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
archived_version = false

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://butler.ptarmiganlabs.com"

# A variable used in various docs to determine URLs for config files etc.
# To find occurrences, search the repo for 'params "githubbranch"'.
githubbranch = "v4.0-branch"

# Add new release versions here. These entries appear in the drop-down menu
# at the top of the website.
[[params.versions]]
  version = "v4.0"
  githubbranch = "master"
  url = "https://butler.ptarmiganlabs.com"

# [[params.versions]]
#   version = "v1.0"
#   githubbranch = "v1.0-branch"
#   url = "https://v1-0-branch.kubeflow.org"

# Docsy: User interface configuration
[params.ui]
# Docsy: Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Docsy: Disable the search box in the side bar.
sidebar_search_disable = true
#  Docsy: Set to true to disable breadcrumb navigation.
breadcrumb_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/ptarmiganlabs/butler/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/ptarmiganlabs/butler/issues/new">tell us how we can improve</a>.'


[params.links]
# Docsy: "User" links will show on left side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/ptarmiganlabs"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news"
[[params.links.user]]
	name = "GitHub"
	url = "https://github.com/ptarmiganlabs/butler"
	icon = "fab fa-github"
        desc = "Development happens here!"
[[params.links.user]]
	name = "LinkedIn"
	url = "https://www.linkedin.com/in/gorsan/"
	icon = "fab fa-linkedin"
        desc = "Reach out to Ptarmigan Labs via LinkedIn"
# [[params.links.user]]
# 	name = "Slack"
# 	url = "https://kubeflow.slack.com/join/shared_invite/zt-cpr020z4-PfcAue_2nw67~iIDy7maAQ"
# 	icon = "fab fa-slack"
#         desc = "Chat with other project contributors"
[[params.links.user]]
	name = "Newsletter"
	url = "https://www.subscribepage.com/g3c1f1"
	icon = "fa fa-envelope"
        desc = "Be the first to hear about Butler news"


# Docsy: "Developer" links will show on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/ptarmiganlabs/butler"
	icon = "fab fa-github"
        desc = "Development takes place here!"

[[params.links.developer]]
	name = "Get in touch with Ptarmigan Labs"
	url = "mailto://info@ptarmiganlabs.com"
	icon = "fa fa-envelope"
        desc = "Get in touch with Ptarmigan Labs around Butler SOS"





[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    # respectDoNotTrack = false
    # useSessionStorage = false
  [privacy.instagram]
    disable = true
    # simple = false
  [privacy.twitter]
    disable = true
    # enableDNT = false
    # simple = false
  [privacy.vimeo]
    disable = true
    # simple = false
  [privacy.youtube]
    disable = true
    # privacyEnhanced = false
	